### PR TITLE
Create spring-hibernate.md

### PR DESCRIPTION
**Pull request by n614cd**
basic steps/directions to use pgroonga with Spring/Hibernate,. I did not include an update to the index page linking to this how-to

### CODE REVIEW

**Comment by kou** [comment]
Thanks!

**Comment by n614cd** [comment]
Welcome, reminder I did not update the index page.

**Comment by kou** [comment]
Could you open one more pull request for the index page?

**Comment by n614cd** [comment]
Done. But this is a guess on my part following the other examples ahead of me. I have never done Github pages.

**Pull request merged**
