### PR TITLE
update tutorial and operators

### PR DESCRIPTION
**Pull request by ologithub**
tutorial:
changed the operators from "%%" "@@" to "&@" "&?" "&`"

operators:
fixed some texts

### CODE REVIEW

**Comment by s-yata** [comment]
Your pull request seems to contain needless binary files named .DS_Store.

**Comment by gunyarakun** [comment]
I think commit messages should more clearly describe what you do.
ref.) http://www.clear-code.com/blog/2013/4/24.html (in Japanese)

**Comment by ologithub** [comment]
* tutorial
  * Replaced operators from `%%` `@@` with `&@` `&?` `` &` `` because `%%` and `@@` are deprecated from version 1.2.1.

* operators
  * query.md 
    * Added definition `[query-v2]:query-v2.html` (link)
  * script-jsonb-v2.md
    * Fixed title

* `DS_Store` files
  * Deleted because these files are needless. Please ignore them.

**Comment by kou** [comment]
Thanks!

Please don't include multiple logical changes in one pull request. Could you split your pull request to two pull requests. 1) Fixing operators documents and 2) updating tutorial.

And, you shouldn't change files in `ja/` directly. They are auto generated files. We can update them by the followings:

```console
% bundle install
% bundle exec rake # _po/ja/** are updated
% editor _po/ja/.../XXX.po.edit
% bundle exec rake # applies _po/ja/** changes to ja/**
```

**Comment by kou** [comment]
Splitting three pull requests are better:

  * query.md: Added definition `[query-v2]:query-v2.html (link)`
  * script-jsonb-v2.md : Fixed title
  * tutorial

**Comment by ologithub** [comment]
OK, I'll try again. Thank you!

**Pull request closed without merging**
